.TH "OXIM" "1" "12 September 2008" "Firefly" "OpenDesktop"
.SH "NAME"
oxim \- The Open X Input Method
.SH "SYNOPSIS"
.RB oxim\ [-h|-d\ DISPLAY|-x\ XIM_name|-v\ n|-r]

.RB oxim\ -h
.br
Get help messages.

.RB oxim\ -d\ DISPLAY
.br
Setting X DISPLAY port.

.RB oxim\ -x\ XIM_name
.br
Register XIM server to Xlib.

.RB oxim\ -v\ n 
.br
Setting debug levels.

.RB oxim\ -r
.br
Reload OXIM.

.SH "DESCRIPTION"
\fIOXIM\fR is a program that afford the service for Chinese input method. It is a improvment base on XCIN 2.5.3pre2. Beside containing advantage of XCIN, it add new nice graphic user interface and more function such that you could type chinese without care about what your choosen language in your system is.
.SH "AUTHOR"
.br 
Firefly <firefly@opendesktop.org.tw>
.SH "REPORTING BUGS"
Report bugs to <firefly@opendesktop.org.tw>
.SH "COPYRIGHT"
Copyright (c) 2006 by  OpenDesktop.org.tw

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111\-1307  USA
.SH "SEE ALSO"
\fBoxim\-setup\fR(1)
.br 
\fBhttp://www.opendesktop.org.tw/demopage/oxim\fR
